### ISSUE TITLE
获取加载完成的状态值问题

### ISSUE THREAD

**Issue by Kabuda-czh** [maptalks/examples#110]
请问如何获取maptalks创建的容器中的内容加载完成的状态值

**Comment by fuzhenn** [comment]
maptalks没有这个状态，因为map的加载是同步而不是异步的，new Map的时候，内容就加载完成了。
但图层有可能是异步加载的，比如TileLayer，图层可以用layerload事件来监听是否完成。
注意，layerload会多次触发，图层只要重绘加载完成后，就会触发这个事件。
```js
layer.once('layerload', e => {});
```
