### ISSUE TITLE
更新Feature的示例调整颜色，并增加highlight方法说明

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/examples#145]
目前两个按钮的颜色都设置成了一样，无法区分开两次highlight的结果。

另外highlight方法只涉及到color,id,filter三个参数，应该在md中说明highlight方法的使用参数。

http://examples.maptalks.com/examples/cn/vector/style/update-feature-style

**Comment by yy923683900** [comment]
fix by 9941fb7b622d477dd4e6e7ef6c594fdecb8925ed
