### ISSUE TITLE
code error 

### ISSUE THREAD

**Issue by deyihu** [maptalks/examples#160]
http://examples.maptalks.com/examples/cn/vector/interactive/altitude

![6~TUG(A~}~82 (0FM ~ 2D](https://github.com/maptalks/examples/assets/25998927/bd530091-42d9-42a7-9c96-8bb2171ed815)

看着像是批量替换导致的
这个错误太低级了
建议：
- 把eslint 加上去
- build 命令里 eslint下来解决这种低级错误

**Comment by fuzhenn** [comment]
fixed
