### ISSUE TITLE
add attribution in templates

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/examples#48]
@wsw0108 除了urlTemplate和subdomains, 还需要加上attribution信息

具体参考
https://github.com/maptalks/raster-collection

**Comment by wsw0108** [comment]
https://github.com/maptalks/examples/tree/attribution

不过每个example都要这么改有点多, 看有没什么模板化的方式.

**Comment by wsw0108** [comment]
模板化的方式不合适.
- 有的例子不适合用像urlTemplate那样提供的attribution

所以最终还是每个例子单独处理.
