### ISSUE TITLE
auto deployment

### ISSUE THREAD

**Issue by wsw0108** [maptalks/examples#50]

**Comment by wsw0108** [comment]
https://docs.travis-ci.com/user/deployment/pages/

**Comment by wsw0108** [comment]
OR
- `mkdir build`
- checkout this repo to `build/demo`
- checkout [docs](https://github.com/maptalks/docs) to `build/docs`
- run `gulp build` under `build/demo`
- run `git -C build/docs commit -a -m "update examples"`
- run `git -C build/docs push --force`, after setup token

**Comment by wsw0108** [comment]
我认为, travis ci的deploy还是简单些.

对于这个repo, 可以改名为maptalks/examples, 然后发布到它的gh-pages分支, 形成`https://maptalks.github.io/examples/en/index.html`这样的url;

对于api文档, 可以发布到maptalks/maptalks.js的gh-pages分支, 也可以新建一个repo, 如maptalks/api;

**Comment by wsw0108** [comment]
CircleCI的deploy也不算是很复杂, [这里](https://github.com/Villanuevand/deployment-circleci-gh-pages/tree/master)有个参考.
- 需要设置[ssh key](https://circleci.com/docs/1.0/github-security-ssh-keys)(machine user key/github user key), 或者OAuth Token. **自行评估三种方式的安全性**.
- circle.yml里的deployment配置
- deployment脚本
- CircleCI的WebUI中的git相关环境变量(如果写在deployment脚本中, 就不需要)

对于发布的目标位置(gh-pages的话), 我觉得仓库自身的gh-pages分支比较好.
@fuzhenn @brucin

**Comment by fuzhenn** [comment]
circleCI目前比较强势, 到处在打广告, 我们还是用circleCI

我也同意按你说的,  把页面发布在仓库自身的gh-pages中.

那就按照你的想法先把examples做一下吧

* 用circleCI
* CI中设置maptalks-doc-robot的ssh key
* 编写脚本, 每次更新时, 自动生成页面并commit到gh-pages分支中

**Comment by fuzhenn** [comment]
API文档的生成有两个选择:
* 按你说的提交到gh-pages分支中
* 每次npm publish时, 在doc目录下生成文档(github支持在master/doc下发布网站)

我感觉第二个选择也不错
