### ISSUE TITLE
取消index.css, 合并index.html和index.js

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/examples#54]
把html/css/js合并显示, 而不再分开, 点击copy后, 即复制整个html页面内容

类似mapbox-gl-js的示例:
https://www.mapbox.com/mapbox-gl-js/examples/

**Comment by wsw0108** [comment]
我也是这么想的，以前那么分开太分裂了

**Comment by wsw0108** [comment]
- 显示是合并的结果
- 复制的是完整的有效的html
- 源码里依然是分开的, 方便jsfiddle的处理

**Comment by fuzhenn** [comment]
👍
