### ISSUE TITLE
code prettify is very slow

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/examples#58]
代码语法高亮的载入速度较慢, 需要优化

**Comment by wsw0108** [comment]
将底图服务地址换成一个连接速度快的, 或者将示例demo[不显示](https://github.com/maptalks/examples/blob/master/layouts/example.hbs#L93), code prettify就不慢了.

**Comment by wsw0108** [comment]
另外, run_prettify.js是自动载入prettify的脚本, 会去cdn.rawgit.com载入prettify.css;
自己提供prettify并手动载入的方法, [在此](https://github.com/google/code-prettify/blob/master/docs/getting_started.md#serving-your-own-js--css).

**Comment by wsw0108** [comment]
另外, run_prettify.js是自动载入prettify的脚本, 会去cdn.rawgit.com载入prettify.css;
自己提供prettify并手动载入的方法, [在此](https://github.com/google/code-prettify/blob/master/docs/getting_started.md#serving-your-own-js--css).

**Comment by fuzhenn** [comment]
看上去是因为prettify会等待[window.onload(或类似)](https://github.com/google/code-prettify/blob/f6c4ce7d5930891815cfaf8839febf48166a9db5/js-modules/run_prettify.js#L116)事件, 再自动执行prettify的

window.onload会等iframe执行完才会执行

我觉得可以试试按你给的文档, 改为手动执行prettify, 试试看能否解决这个问题.

**Comment by wsw0108** [comment]
手动载入也是需要在onload里执行`PR.prettyPrint()`, 否则pretty的目标code/pre会没有准备好.
这个算是网络问题.

**Comment by fuzhenn** [comment]
可以试试body.onload
有的资料上说, body.onload在大多数浏览器不会等待iframe的onload, 但window.onload会

或者可以试试在prettify之后后, 再设置iframe的src
